import AuthButton from "@/components/AuthButton"
import Head from "next/head"

export default async function HomePage() {
  return (
    <>
      <Head>
        <title>Learnsight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col w-full h-screen justify-center items-center gap-4 bg-background text-foreground">
        <h1 className="text-5xl font-bold">
          Welcome to <a href="https://learnsight.io">Learnsight</a>
        </h1>

        <p className="text-2xl text-gray-200">
          A collaborative learning tool for live training 😍
        </p>
        <AuthButton />
      </main>
    </>
  )
}
