import { UseQueryProvider } from "@/utils/use-query-provider";
import "../../../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full w-full scrollbar-thin scrollbar-thumb-indigo-700 scrollbar-track-white scrollbar-track-rounded-full">
        <UseQueryProvider>{children}</UseQueryProvider>
      </body>
    </html>
  );
}
