import { UseQueryProvider } from "@/utils/use-query-provider";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ModalProvider } from "@/providers/modal-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body classname="h-full w-full scrollbar-thin scrollbar-thumb-indigo-700 scrollbar-track-white scrollbar-track-rounded-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={false}
          storageKey="elearning"
        >
          <UseQueryProvider>
            {children}
            <ModalProvider />
          </UseQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
